spring:
    data:
        mongodb:
            host: ${openshift.mongodb.db.host}
            port: ${openshift.mongodb.db.port}
            database: ${openshift.app.name}
            username: ${openshift.mongodb.db.username}
            password: ${openshift.mongodb.db.password}
    mail:
        host: "smtp.gmail.com"
        username: "moso.sender@gmail.com"
        password: "idriwoutevbzkjxy"
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
                    starttls:
                        enabled: true
                        required: false
