spring:
    data:
        mongodb:
            host: "127.6.248.2"
            port: 27017
            database: "secretsanta"
            username: ${openshift.mongodb.db.username}
            password: ${openshift.mongodb.db.password}