spring:
    data:
        mongodb:
            host: "$OPENSHIFT_MONGODB_DB_HOST"
            port: "$OPENSHIFT_MONGODB_DB_PORT"
            database: "secretsanta"
            user: "$OPENSHIFT_MONGODB_USERNAME"
            password: "$OPENSHIFT_MONGODB_USERNAME"