spring:
    data:
        mongodb:
            host: ${openshift.mongodb.db.host}
            port: ${openshift.mongodb.db.port}
            database: ${openshift.app.name}
            username: ${openshift.mongodb.db.username}
            password: ${openshift.mongodb.db.password}